---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - name: Loading environment variables
      tags: always
      set_fact:
        ANSIBLE_HOST_KEY_CHECKING=False 
        ENVIROMENT=production
        NODE_ENV=production     
        TYPEORM_CONNECTION=postgres
        TYPEORM_MIGRATIONS_DIR=./src/migrations
        TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts         
        TYPEORM_PORT=5432
        TYPEORM_USERNAME=postgres     
        TYPEORM_PASSWORD=mypassword
        TYPEORM_DATABASE=udapeople_prod
        TYPEORM_HOST=udapeople-bleedprod.c9x9nxt1oxxy.us-east-1.rds.amazonaws.com
  roles:
    - deploy
